config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :courses do
    member do
      post 'join', action: :join
    end
  end

  resources :subjects do
    collection do
      post 'join', action: :join
      delete 'destroy_attachment', action: :destroy_attachment
    end
  end

  resources :users
  resources :subjects_documents, :only => [:destroy]


  root controller: :courses, action: :index
  
  get '/register', to: 'users#new' 
  post '/register', to: 'users#create' 

  get    '/login',   to: 'auth#new'   
  post   '/login',   to: 'auth#create'   
  delete '/logout',  to: 'auth#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  address         :string
#  avatar_url      :string
#  birthday        :datetime
#  deleted_at      :datetime
#  email           :string           not null
#  fullname        :string
#  password_digest :string           not null
#  role            :integer          not null
#  created_at      :datetime
#  updated_at      :datetime
#
class User < ApplicationRecord

    has_secure_password
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true

    has_many :courses, dependent: :destroy

    has_many :users_courses
    has_many :users_subjects
  
    enum role: {
	user: 0,
	admin: 10
    }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_action :load_resources

    def index
        @users = params.include?('in-active') ? pagination( User.only_deleted) : pagination(User.all)
    end

    def new
         @user= User.new
    end

    def edit       
    end

    def update
        if  @user.update(write_params)
            flash[:success] = "Update Profile Success"
        else
            flash.now[:danger] = @user.errors.full_messages.first
        end
        render 'edit'
    end

    def show
        @courses = pagination(current_user.users_courses.map(&:course))
    end

    def create 
        if @user.save
            sign_in @user 
            flash[:success] = "Welcome to #{@user.fullname}"
            redirect_to @user
        else

            flash.now[:danger] = @user.errors.full_messages.first
            render 'new'
        end
    end

    def destroy
        @user = User.unscoped.where(id: params[:id]).first
        if @user.deleted_at.nil?
            @user.destroy
            flash[:success] = "Block #{@user.fullname} success!"
        else
            @user.assign_attributes(deleted_at: nil)
            @user.save
            flash[:success] = "Unlock #{@user.fullname} success!"
        end
        redirect_to users_url
    end

    private


    def load_resources
      case params[:action].to_sym
      when :index, :show, :destroy
          @new_course = Course.limit(3)
      when :edit, :update
          @user = User.unscoped.where(id: params[:id]).first
      when :create
          @user = User.new(write_params)
      end
    end

    def write_params
        params.require(:user).permit(
          :fullname,
          :email,
          :password,
          :birthday,
          :avatar_url,
          :address,
          :role
        )
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_right.html.erb
<div class="col-lg-3 col-md-4 col-sm-12 m-b30">
   <div class="profile-bx text-center">
      <div class="user-profile-thumb">
         <%= image_tag "profile/pic1.jpg" %>
      </div>
      <div class="profile-info">
         <h4><%= current_user.fullname%></h4>
         <span><%= current_user.email%></span>
      </div>
      <div class="profile-social">
         <ul class="list-inline m-a0">
            <li><a href="#"><i class="fab fa-facebook"></i></a></li>
            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fab fa-google-plus"></i></a></li>
         </ul>
      </div>
      <div class="profile-tabnav">
         <ul class="nav nav-tabs">
            <li class="nav-item">
               <%= link_to  current_user,class: "nav-link active" do %>
               <i class="ti-book"></i> Courses
               <% end %>
            </li>
            <li class="nav-item">
               <%= link_to edit_user_path(current_user), class: "nav-link" do %>
               <i class="ti-pencil-alt" aria-hidden="true"></i> Edit Profile
               <% end %>
            </li>
            <li class="nav-item">
               <a class="nav-link" data-toggle="tab" href="#change-password"><i class="ti-lock"></i>Change Password</a>
            </li>
         </ul>
      </div>
   </div>
</div>

app/views/users/edit.html.erb
<div class="page-content bg-white">
   <!-- inner page banner -->
   <div class="page-banner ovbl-dark">
      <div class="container">
         <div class="page-banner-entry">
            <h1 class="text-white">Edit Profile</h1>
         </div>
      </div>
   </div>
   <!-- Breadcrumb row -->
   <div class="breadcrumb-row">
      <div class="container">
         <ul class="list-inline">
            <li><i class="fa fa-home"></i><a href="/">  Edit</a></li>
            <i class="fa fa-angle-right"></i>
            <li>Profile</li>
         </ul>
      </div>
   </div>
   
   <!-- Breadcrumb row END -->
   <!-- inner page banner END -->
   <div class="content-block">
      <!-- About Us -->
      <div class="section-area section-sp1">
         <div class="container">
            <div class="row">
               <%= render 'users/right'%>
               <div class="col-lg-9 col-md-8 col-sm-12">
                  <div class="profile-head">
                     <h3>Edit Profile</h3>
                  </div>
                  <div >
                     <div class="tab-pane" id="edit-profile">
                        <%= form_with model: @user, scope: "post", :html => { class: "edit-profile" }, local: true  do |form| %>
                        <div class="">
                           <div class="form-group row">
                              <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">Full Name</label>
                              <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                                 <input class="form-control" type="text" readonly name="user[email]" value="<%= @user.email %>">
                              </div>
                           </div>
                           <div class="form-group row">
                              <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">Full Name</label>
                              <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                                 <input class="form-control" type="text" name="user[fullname]" value="<%= @user.fullname %>">
                              </div>
                           </div>
                           <div class="form-group row">
                              <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">Birthday</label>
                              <div class="col-12 col-sm-9 col-md-9 col-lg-7 d-flex">
                                 <input class="form-control" type="date" name="user[birthday]" value="<%=  @user.birthday.to_s.split(" ").first %>">
                                 <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">Role</label>
                                 <% if current_user.role.eql?('admin') %>
                                 <select name="user[role]" class="form-control" id="exampleFormControlSelect1">
                                    <option value="admin">ADMIN</option>
                                    <option value="user">USER</option>
                                 </select>
                                 <% else %>
                                 <input class="form-control" type="text" readonly name="user[role]" value="<%= @user.role %>">
                                 <% end %>
                              </div>
                           </div>
                           <div class="form-group row">
                              <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">Address</label>
                              <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                                 <input class="form-control" type="text" name="user[address]" value="<%= @user.address %>">
                                 <span class="help">If you want your invoices addressed to a company. Leave blank to use your full name.</span>
                              </div>
                           </div>
                           <!--
                              <%# <div class="form-group row">
                                 <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">avatar_url</label>
                                 <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                                    <input class="form-control" type="text" name="user[avatar_url]" value="<%= @user.avatar_url %>">
                                </div>
                              </div>
                              -->
                        </div>
                        <div class="">
                           <div class="">
                              <div class="row">
                                 <div class="col-12 col-sm-3 col-md-3 col-lg-2">
                                 </div>
                                 <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                                    <button type="reset" class="btn btn-dark">Cancel</button>
                                    <%= form.submit "Save changes", class: "btn btn-warning" %>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <% end %>
                     </div>
                  </div>
                  <div class="profile-head">
                     <h3>Edit Password</h3>
                  </div>
                  <div class="tab-pane" id="edit-profile">
                     <%= form_with model: @user, scope: "post", :html => { class: "edit-profile" }, local: true  do |form| %>
                     <div class="">
                        <div class="form-group row">
                           <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">New Password</label>
                           <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                              <input class="form-control" type="text" name="user[password]"  >
                           </div>
                        </div>
                        <div class="form-group row">
                           <label class="col-12 col-sm-3 col-md-3 col-lg-2 col-form-label">Pasword Confirm</label>
                           <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                              <input class="form-control" type="text" name="user[avatar_url]" >
                           </div>
                        </div>
                        <div class="">
                           <div class="">
                              <div class="row">
                                 <div class="col-12 col-sm-3 col-md-3 col-lg-2">
                                 </div>
                                 <div class="col-12 col-sm-9 col-md-9 col-lg-7">
                                    <button type="reset" class="btn btn-dark">Cancel</button>
                                    <%= form.submit "Save changes", class: "btn btn-warning" %>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <% end %>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- contact area END -->
</div>

app/views/users/index.html.erb
<!-- header END ==== -->
<!-- Content -->
<div class="page-content bg-white">
<!-- inner page banner -->
<div class="page-banner ovbl-dark" >
   <div class="container">
      <div class="page-banner-entry">
         <h1 class="text-white">List Member</h1>
      </div>
   </div>
</div>
<!-- Breadcrumb row -->
<div class="breadcrumb-row">
   <div class="container">
      <ul class="list-inline">
         <li><i class="fa fa-home"></i><a href="/">  Home</a></li>
         <i class="fa fa-angle-right"></i>
         <li>List Member</li>
      </ul>
   </div>
</div>
<!-- Breadcrumb row END -->
<!-- inner page banner END -->
<div class="content-block">
   <!-- About Us -->
   <div class="section-area section-sp1">
      <div class="container">
         <div class="row">
            <%= render 'layouts/nav'%>
            <div class="col-lg-9 col-md-8 col-sm-12">
               <div class="tab-content">
                  <div class="tab-pane active" id="courses">
                     <div class="feature-filters style1 ml-auto">
                        <ul class="filters" data-toggle="buttons">
                           <li data-filter="" class="btn active">
                              <input type="radio">
                              <a href="?active"><span>Active</span></a> 
                           </li>
                           <li data-filter="publish" class="btn">
                              <input type="radio">
                              <a href="?in-active"><span>In-Active</span></a> 
                           </li>
                        </ul>
                     </div>
                  </div>
                  <div class="row">
                     <% @users.each  do | user | %>
                     <div class="col-md-6 col-lg-4 col-sm-6 m-b30" >
                        <div class="profile-bx text-center">
                           <div class="user-profile-thumb">
                              <%= image_tag "profile/pic1.jpg" %>
                           </div>
                           <div class="profile-info">
                              <h4><%= user.fullname %></h4>
                              <span><%= user.email %></span>
                           </div>
                           <div class="profile-social">
                              <ul class="list-inline m-a0">
                                 <li><a href="#"><i class="fab fa-facebook"></i></a></li>
                                 <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                 <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                                 <li><a href="#"><i class="fab fa-google-plus"></i></a></li>
                              </ul>
                           </div>
                           <div class="profile-tabnav">
                              <%= link_to edit_user_path(user.id), class: "btn btn-info" do %>
                              <i class="fa fa-pencil-square-o" aria-hidden="true"></i> &nbsp; Detail
                              <% end %>
                              <%= link_to user_path(user), class: "btn #{user.deleted_at.nil? ? 'btn-dark' : 'btn-warning'}", method: :delete, data: {confirm: "ARE YOU SURE #{user.deleted_at.nil? ? 'BLOCK' : 'UNLOCK'}: #{  user.fullname} ?"} do %>
                              <i class="fa fa-lock" aria-hidden="true"></i> &nbsp; Block
                              <% end %>

                           </div>
                        </div>
                     </div>
                     <% end %>
                  </div>
               </div>
               <div class="col-lg-12 m-b20">
                  <div class="pagination-bx rounded-sm gray clearfix">
                     <ul class="pagination">
                        <div class="paginate paginate-default paginate-link">
                           <% if @users.present? %>
                           <%= paginate @users %>
                           <% end %>
                        </div>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- contact area END -->
</div>

app/views/users/new.html.erb
<div class="page-wraper">
   <div class="account-form">
      <div class="account-head" style="background-image:url(assets/images/background/bg2.jpg);">
      </div>
      <div class="account-form-inner">
         <div class="account-container">
            <div class="heading-bx left">
               <h2 class="title-head">Sign Up <span>Now</span></h2>
               <p>Login Your Account <%= link_to "Click here", login_path %></p>
            </div>
            <%= form_with(url: "/register",class: "contact-bx" ,method: "post") do %>
            <div class="row placeani">
               <div class="col-lg-12">
                  <div class="form-group">
                     <div class="input-group">
                        <input placeholder="Fullname" name="user[fullname]" type="text" required="" class="form-control">
                     </div>
                  </div>
               </div>
               <div class="col-lg-12">
                  <div class="form-group">
                     <div class="input-group">
                        <input name="user[email]" placeholder="Email Address" type="email" required="" class="form-control">
                     </div>
                  </div>
               </div>
               <input name="user[role]" type="hidden" value="user">
               <div class="col-lg-12">
                  <div class="form-group">
                     <div class="input-group"> 
                        <input placeholder="Password" name="user[password]" type="password" class="form-control" required="">
                     </div>
                  </div>
               </div>
               <div class="col-lg-12 m-b30">
                  <button name="submit" type="submit" value="Submit" class="btn btn-warning button-md">Sign Up</button>
               </div>
            </div>
            <% end %>
         </div>
      </div>
   </div>
</div>

app/views/users/show.html.erb
<div class="page-content bg-white">
   <!-- inner page banner -->
   <div class="page-banner ovbl-dark">
      <div class="container">
         <div class="page-banner-entry">
            <h1 class="text-white">Infomation</h1>
         </div>
      </div>
   </div>
   <!-- Breadcrumb row -->
   <div class="breadcrumb-row">
      <div class="container">
         <ul class="list-inline">
            <li><i class="fa fa-home"></i><a href="/">  Home</a></li>
            <i class="fa fa-angle-right"></i>
            <li>Profile</li>
         </ul>
      </div>
   </div>
   <!-- Breadcrumb row END -->
   <!-- inner page banner END -->
   <div class="content-block">
      <!-- About Us -->
      <div class="section-area section-sp1">
         <div class="container">
            <div class="row">
               <%= render 'users/right'%>
               <div class="col-lg-9 col-md-8 col-sm-12">
                  <div class="row">
                     <% if  @courses.count.zero? %>
                     <h1 style="margin: auto;"> No Course Yet </h1>
                     <% else %>
                     <% @courses.each  do | course | %>
                     <div class="col-md-6 col-lg-4 col-sm-6 m-b30">
                        <div class="cours-bx">
                           <% if signed_in? %>
                           <% if current_user.role.eql?('admin') %>
                           <%= link_to course_path(course), class: "remove-course", method: :delete, data: {confirm: "ARE YOU SURE DELETE COURSE: #{  course.title} ?"} do %>
                           <i class="fa fa-times-circle text-danger" aria-hidden="true"></i>
                           <% end %>
                           <% end %>
                           <% end %>
                           <div class="action-box">
                              <%= image_tag course.thumb_url.url, style:"height: 153px !important" %>
                              <a href="#" class="btn">Read More</a>
                           </div>
                           <div class="info-bx text-center">
                              <h6><a class="course-title" href="/courses/<%= course.id %>"><%= course.title %></a></h6>
                              <span><%= course.category %></span>
                           </div>
                           <div class="cours-more-info">
                              <div class="review">
                                 <ul class="cours-star">
                                    <li class="active"><i class="fa fa-list-alt" aria-hidden="true"></i> Category </li>
                                 </ul>
                                 <span><%= course.category %></span>
                              </div>
                              <div class="price">
                                 <span><i class="fas fa-shopping-cart"></i> Price</span>
                                 <h6>$<%= course.price %></h6>
                              </div>
                           </div>
                        </div>
                     </div>
                     <% end %>
                     <% end %>
                     <div class="col-lg-12 m-b20">
                        <div class="pagination-bx rounded-sm gray clearfix">
                           <ul class="pagination">
                              <div class="paginate paginate-default paginate-link">
                                 <% if @courses.present? %>
                                 <%= paginate @courses %>
                                 <% end %>
                              </div>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- contact area END -->
</div>