config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :courses do
    member do
      post 'join', action: :join
    end
  end

  resources :subjects do
    collection do
      post 'join', action: :join
      delete 'destroy_attachment', action: :destroy_attachment
    end
  end

  resources :users
  resources :subjects_documents, :only => [:destroy]


  root controller: :courses, action: :index
  
  get '/register', to: 'users#new' 
  post '/register', to: 'users#create' 

  get    '/login',   to: 'auth#new'   
  post   '/login',   to: 'auth#create'   
  delete '/logout',  to: 'auth#destroy'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate, only: [:create,:new,:destroy,:join]
  before_action :load_resources

  def index
    if params[:search].present?
      @courses = pagination(Course.search(params[:search]))

    else
      @courses = pagination(Course.by_category(params[:condition]))
    end
  end
  
  def show
  end

  def new
  end

  def create
	 if @course.save
      flash[:success] = "Create Success !"
      redirect_to root_path      
    else
      flash[:danger] = "#{@course.errors.full_messages.first}"
      render  'new'
    end
	end

  def join
    if is_joined_course?(@course)
      current_user.users_courses.create!(course: @course)
      flash[:success] = "Wellcome to join with us!"
    else
      current_user.users_courses.joined(@course).delete_all
      current_user.users_subjects.where(course_id: @course.id).delete_all    
      flash[:danger] = "Leave Success!"
    end
    redirect_to  action: 'show', id: @course.id

  end

  def destroy
    if @course.destroy
      flash[:success] = "Delete Success !"
    else
      flash[:danger] = "Something Wrong !"
    end
      redirect_to root_path
  end

  private

  def load_resources
    case params[:action].to_sym
    when :index, :new
      @new_course = Course.limit(3)
    when :join, :show, :destroy
      @course = Course.find(params[:id])
      is_joined_course?(@course)
    when :create
      @course = current_user.courses.new(write_params)
    end
  end


	def write_params
    params.require(:course).permit(
      :title,
      :category,
      :thumb_url,
      :price,
      :description
    )
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<!-- header END ==== -->
<!-- Content -->
<div class="page-content bg-white">
   <!-- inner page banner -->
   <div class="page-banner ovbl-dark" >
      <div class="container">
         <div class="page-banner-entry">
            <h1 class="text-white">Our Courses</h1>
         </div>
      </div>
   </div>
   <!-- Breadcrumb row -->
   <div class="breadcrumb-row">
      <div class="container">
         <ul class="list-inline">
            <li><i class="fa fa-home"></i><a href="/">  Home</a></li>
            <i class="fa fa-angle-right"></i>
            <li>Our Courses</li>
         </ul>
      </div>
   </div>
   <!-- Breadcrumb row END -->
   <!-- inner page banner END -->
   <div class="content-block">
      <!-- About Us -->
      <div class="section-area section-sp1">
         <div class="container">
            <div class="row">
               <%= render 'layouts/nav'%>
               <div class="col-lg-9 col-md-8 col-sm-12">
                  <div class="row">
                     <% if  @courses.count.zero? %>
                     <h1 style="margin: auto;"> No Course Yet </h1>
                     <% else %>
                     <% @courses.each  do | course | %>
                     <div class="col-md-6 col-lg-4 col-sm-6 m-b30">
                        <div class="cours-bx">
                           <% if signed_in? %>
                           <% if current_user.role.eql?('admin') %>
                           <%= link_to course_path(course), class: "remove-course", method: :delete, data: {confirm: "ARE YOU SURE DELETE COURSE: #{  course.title} ?"} do %>
                           <i class="fa fa-times-circle text-danger" aria-hidden="true"></i>
                           <% end %>
                           <% end %>
                           <% end %>
                           <div class="action-box">
                              <%= image_tag course.thumb_url.url, style:"height: 153px !important" %>
                              <a href="#" class="btn">Read More</a>
                           </div>
                           <div class="info-bx text-center">
                              <h6><a class="course-title" href="courses/<%= course.id %>"><%= course.title %></a></h6>
                              <span><%= course.category %></span>
                           </div>
                           <div class="cours-more-info">
                              <div class="review">
                                 <ul class="cours-star">
                                    <li class="active"><i class="fa fa-list-alt" aria-hidden="true"></i> Category </li>
                                 </ul>
                                 <span><%= course.category %></span>
                              </div>
                              <div class="price">
                                 <span><i class="fas fa-shopping-cart"></i> Price</span>
                                 <h6>$<%= course.price %></h6>
                              </div>
                           </div>
                        </div>
                     </div>
                     <% end %>
                     <% end %>
                     <div class="col-lg-12 m-b20">
                        <div class="pagination-bx rounded-sm gray clearfix">
                           <ul class="pagination">
                              <div class="paginate paginate-default paginate-link">
                                 <% if @courses.present? %>
                                 <%= paginate @courses %>
                                 <% end %>
                              </div>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- contact area END -->
</div>

app/views/courses/new.html.erb
<!-- header END ==== -->
<!-- Content -->
<div class="page-content bg-white">
   <!-- inner page banner -->
   <div class="page-banner ovbl-dark" >
      <div class="container">
         <div class="page-banner-entry">
            <h1 class="text-white">New Courses</h1>
         </div>
      </div>
   </div>
   <!-- Breadcrumb row -->
   <div class="breadcrumb-row">
      <div class="container">
         <ul class="list-inline">
            <li><i class="fa fa-home"></i><a href="/">  Home</a></li>
            <i class="fa fa-angle-right"></i>
            <li>New Courses</li>
         </ul>
      </div>
   </div>
   <!-- Breadcrumb row END -->
   <!-- inner page banner END -->
   <div class="content-block">
      <!-- About Us -->
      <div class="section-area section-sp1">
         <div class="container">
            <div class="row">
               <%= render 'layouts/nav'%>
               <div class="col-lg-9 col-md-8 col-sm-12">
                  <%= form_with(url: "/courses", method: "post", local: true ,html: { multipart: true }) do %>
                  <div class="ajax-message"></div>
                  <div class="heading-bx left p-r15">
                     <h2 class="title-head">Share A <span>Course</span></h2>
                     <p>Market and sell your courses with a full suite of business tools. 
                        <br>
                        Thousands of entrepreneurs trust Thinkific for exceptional student experiences
                     </p>
                  </div>
                  <div class="row placeani">
                     <div class="col-lg-8">
                        <div class="col-lg-12 ">
                           <div class="form-group">
                              <div class="input-group">
                                 <input placeholder="Title" name="course[title]" type="text" required="" class="form-control valid-character">
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-12">
                           <div class="form-group">
                              <div class="input-group">
                                 <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                 </div>
                                 <input  placeholder="Price" name="course[price]" type="number" required=""  class="form-control int-value"> 
                                 <div class="input-group-append">
                                    <span class="input-group-text">.00</span>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-12">
                           <div class="form-group">
                              <div class="input-group">
                                 <select style="height: 52px;" name="course[category]"  class="form-control" >
                                    <option value="IT - Software">IT - Software</option>
                                    <option value="Photography">Photography</option>
                                    <option value="Programming">Programming</option>
                                    <option value="Technology">Technology</option>
                                 </select>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4">
                        <div class="col-lg-12">
                           <div class="form-group">
                              <div class="upload-preview">
                                 <%= image_tag "blog/thumb-default.png", id: "image_preview", onclick: "document.getElementById('getFile').click()"  %>
                                 <input required="" id="getFile" placeholder="Thumbnail" name="course[thumb_url]" type="file"  onchange="readImage(this)" class="inline_image">
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-12">
                        <div class="form-group">
                           <div class="input-group">
                              <textarea placeholder="Description" name="course[description]" rows="4" class="form-control"  ></textarea>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-12">
                        <button name="submit" type="submit" value="Submit" class="btn btn-warning button-md"> Create</button>
                     </div>
                  </div>
                  <% end %>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- contact area END -->
</div>

app/views/courses/show.html.erb
<!-- header END ==== -->
<!-- Content -->
<div class="page-content bg-white">
   <!-- inner page banner -->
   <div class="page-banner ovbl-dark" >
      <div class="container">
         <div class="page-banner-entry">
            <h1 class="text-white">Courses Detail</h1>
         </div>
      </div>
   </div>
   <!-- Breadcrumb row -->
   <div class="breadcrumb-row">
      <div class="container">
         <ul class="list-inline">
            <li><i class="fa fa-home"></i><a href="/">  Home</a></li><i class="fa fa-angle-right"></i>
            <li>Courses Detail</li>
         </ul>
      </div>
   </div>
   <!-- Breadcrumb row END -->
   <input type="hidden" id="ids_hash" value="<%= @ids_hash %>"> 
   <!-- inner page banner END -->
   <div class="content-block">
      <!-- About Us -->
      <div class="section-area section-sp1">
         <div class="container">
            <div class="row d-flex flex-row-reverse">
               <div class="col-lg-3 col-md-4 col-sm-12 m-b30">
                  <div class="course-detail-bx">
                     <div class="course-price">
                        <h4 class="price">$<%= @course.price %></h4>
                     </div>
                     <div class="course-buy-now text-center">
                        <% if signed_in? %>
                        <% if is_joined_course?(@course) %>
                        <%= link_to "Join This Courses", join_course_path(@course), class: "btn btn-warning radius-xl text-uppercase", method: :post %>
                        <% else %>
                        <%= link_to "Leave Courses", join_course_path(@course), class: "btn btn-danger radius-xl text-uppercase", method: :post,data: {:confirm => 'Are you sure leave this course?'} %>
                        <% end %>
                        <% else %>
                        <%= link_to "Join This Courses", join_course_path(@course), class: "btn btn-warning radius-xl text-uppercase", method: :post %>
                        <% end %>
                     </div>
                     <div class="teacher-bx">
                        <div class="teacher-info">
                           <div class="teacher-thumb">
                               <%= image_tag "testimonials/pic1.jpg" %>
                           </div>
                           <div class="teacher-name">
                              <h5><%= @course.user.fullname %></h5>
                              <span>Science Teacher</span>
                           </div>
                        </div>
                     </div>
                        <div class="teacher-bx">
                        <span>Process: <%= percentage(@course)[:completed] %> &#47; <%= percentage(@course)[:totals] %> subjects</span>
                        <div class="teacher-info">
                         <div class="progress w-100">
                           <div class="progress-bar striped-progress-bar" style="width: <%= percentage(@course)[:percentage] %>%"><%= percentage(@course)[:percentage] %>%</div>
                        </div>
                        </div>
                     </div>

                     <div class="course-info-list scroll-page">
                        <ul class="navbar">
                           <li><a class="nav-link" href="#overview"><i class="ti-zip"></i>Overview</a></li>
                           <li><a class="nav-link" href="#curriculum"><i class="ti-bookmark-alt"></i>Curriculum</a></li>
                           <li><a class="nav-link" href="#instructor"><i class="ti-user"></i>Instructor</a></li>
                           <li><a class="nav-link" href="#reviews"><i class="ti-comments"></i>Reviews</a></li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="col-lg-9 col-md-8 col-sm-12">
                  <div class="courses-post">
                     <div class="ttr-post-media media-effect">
                        <%= image_tag @course.thumb_url.url, style:"height: 500px !important" %>
                        <%# <a href="#"><img src="assets/images/blog/default/thum1.jpg" alt=""></a> %>
                     </div>
                     <div class="ttr-post-info">
                        <div class="ttr-post-title ">
                           <h2 class="post-title"><%= @course.title%></h2>
                        </div>
                        <div class="ttr-post-text">
                           <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        </div>
                     </div>
                  </div>
                  <div class="courese-overview" id="overview">
                     <h4>Overview</h4>
                     <div class="row">
                        <div class="col-md-12 col-lg-4">
                           <ul class="course-features">
                              <li><i class="ti-book"></i> <span class="label">Subjects</span> <span class="value"><%= @course.subjects.count %> subjects</span></li>
                              <li><i class="ti-help-alt"></i> <span class="label">Category</span> <span class="value"><%= @course.category %></span></li>
                              <li><i class="ti-time"></i> <span class="label">Duration</span> <span class="value"><%= @course.subjects.sum(:time) %> hours</span></li>
                              <li><i class="ti-stats-up"></i> <span class="label">Skill level</span> <span class="value">Beginner</span></li>
                              <li><i class="ti-user"></i> <span class="label">Students</span> <span class="value"><%= @course.users_courses.count %> member</span></li>
                           </ul>
                        </div>
                        <div class="col-md-12 col-lg-8">
                           <h5 class="m-b5">Course Description</h5>
                           <p><%= @course.description %></p>
                           <h5 class="m-b5">Learning Outcomes</h5>
                           <%= form_with(url: "/subjects/join?course_id=#{ @course.id }", method: "post") do %>
                           <ul class="list-unstyled">

                              <% @course.subjects.each do | subject| %>
                              <%= build_subjects_collection(subject) %>
                              <% end %>

                           </ul>
                           <% end %>
                        </div>
                     </div>
                  </div>
                  <div class="m-b30" id="curriculum">
                     <h4>Curriculum</h4>
                     <ul class="curriculum-list">
                        <% @course.subjects.each do | subject| %>
                        <li>
                           <h5 class="text-dark">
                              <%= link_to subject_path(subject), method: :delete, data: {confirm: "ARE YOU SURE DELETE SUBJECT: #{ subject.name }?"} do %>
                              <i class="fa fa-times-circle text-danger" aria-hidden="true"></i>
                              <% end %>
                              &nbsp;
                              <%= subject.name%>
                           </h5>
                           <ul>
                              <% subject.subjects_documents.each_with_index do | document, index | %>
                              <li>
                                 <div class="curriculum-list-box">
                                    <span>Lesson <%= index %>
                                    <%= link_to document.documents.file.filename , root_url+ document.documents.url, download: true,target: '_self' %>
                                    </span> 
                                 </div>
                                 <% if signed_in? %>
                                 <% if current_user.role.eql?('admin') %>
                                 <%= link_to destroy_attachment_subjects_path(document, "course_id":@course.id ), method: :delete, data: {confirm: "ARE YOU SURE DELETE ATTACHMENT: #{document.documents.file.filename} ?"} do %>
                                 <i class="fa fa-times-circle text-danger" aria-hidden="true"></i>
                                 <% end %>
                                 <% end %>
                                 <% end %>
                              </li>
                              <% end %>	
                           </ul>
                        </li>
                        <% end %>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- contact area END -->
</div>
<!-- contact area END -->
</div>