config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :courses do
    member do
      post 'join', action: :join
    end
  end

  resources :subjects do
    collection do
      post 'join', action: :join
      delete 'destroy_attachment', action: :destroy_attachment
    end
  end

  resources :users
  resources :subjects_documents, :only => [:destroy]


  root controller: :courses, action: :index
  
  get '/register', to: 'users#new' 
  post '/register', to: 'users#create' 

  get    '/login',   to: 'auth#new'   
  post   '/login',   to: 'auth#create'   
  delete '/logout',  to: 'auth#destroy'

end

app/views/layouts/_footer.html.erb
<footer>
   <div class="footer-top">
      <div class="pt-exebar">
         <div class="container">
            <div class="d-flex align-items-stretch">
               <div class="pt-logo mr-auto">
                  <%=image_tag("logo-white.png")%> 
               </div>
               <div class="pt-social-link">
                  <ul class="list-inline m-a0">
                     <li><a href="#" class="btn-link"><i class="fab fa-facebook"></i></a></li>
                     <li><a href="#" class="btn-link"><i class="fab fa-twitter"></i></a></li>
                     <li><a href="#" class="btn-link"><i class="fab fa-linkedin"></i></a></li>
                     <li><a href="#" class="btn-link"><i class="fab fa-google-plus"></i></a></li>
                  </ul>
               </div>
               <div class="pt-btn-join">
                  <a href="#" class="btn ">Join Now</a>
               </div>
            </div>
         </div>
      </div>
      <div class="container">
         <div class="row">
            <div class="col-lg-4 col-md-12 col-sm-12 footer-col-4">
               <div class="widget">
                  <h5 class="footer-title">Sign Up For A Newsletter</h5>
                  <p class="text-capitalize m-b20">Weekly Breaking news analysis and cutting edge advices on job searching.</p>
                  <div class="subscribe-form m-b20">
                     <form class="subscription-form" action="http://educhamp.themetrades.com/demo/assets/script/mailchamp.php" method="post">
                        <div class="ajax-message"></div>
                        <div class="input-group">
                           <input name="email" required="required"  class="form-control" placeholder="Your Email Address" type="email">
                           <span class="input-group-btn">
                           <button name="submit" value="Submit" type="submit" class="btn"><i class="fa fa-arrow-right"></i></button>
                           </span> 
                        </div>
                     </form>
                  </div>
               </div>
            </div>
            <div class="col-12 col-lg-5 col-md-7 col-sm-12">
               <div class="row">
                  <div class="col-4 col-lg-4 col-md-4 col-sm-4">
                     <div class="widget footer_widget">
                        <h5 class="footer-title">Company</h5>
                        <ul>
                           <li><a href="index.html">Home</a></li>
                           <li><a href="about-1.html">About</a></li>
                           <li><a href="faq-1.html">FAQs</a></li>
                           <li><a href="contact-1.html">Contact</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-4 col-lg-4 col-md-4 col-sm-4">
                     <div class="widget footer_widget">
                        <h5 class="footer-title">Get In Touch</h5>
                        <ul>
                           <li><a href="http://educhamp.themetrades.com/admin/index.html">Dashboard</a></li>
                           <li><a href="blog-classic-grid.html">Blog</a></li>
                           <li><a href="portfolio.html">Portfolio</a></li>
                           <li><a href="event.html">Event</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-4 col-lg-4 col-md-4 col-sm-4">
                     <div class="widget footer_widget">
                        <h5 class="footer-title">Courses</h5>
                        <ul>
                           <li><a href="courses.html">Courses</a></li>
                           <li><a href="courses-details.html">Details</a></li>
                           <li><a href="membership.html">Membership</a></li>
                           <li><a href="profile.html">Profile</a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
            <div class="col-12 col-lg-3 col-md-5 col-sm-12 footer-col-4">
               <div class="widget widget_gallery gallery-grid-4">
                  <h5 class="footer-title">Our Gallery</h5>
                  <ul class="magnific-image">
                     <li><a href="assets/images/gallery/pic1.jpg" class="magnific-anchor"><%=image_tag("gallery/pic1.jpg")%>  </a></li>
                     <li><a href="assets/images/gallery/pic2.jpg" class="magnific-anchor"><%=image_tag("gallery/pic2.jpg")%> </a></li>
                     <li><a href="assets/images/gallery/pic3.jpg" class="magnific-anchor"><%=image_tag("gallery/pic3.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic4.jpg" class="magnific-anchor"><%=image_tag("gallery/pic4.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic5.jpg" class="magnific-anchor"><%=image_tag("gallery/pic5.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic6.jpg" class="magnific-anchor"><%=image_tag("gallery/pic6.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic7.jpg" class="magnific-anchor"><%=image_tag("gallery/pic7.jpg")%></a></li>
                     <li><a href="assets/images/gallery/pic8.jpg" class="magnific-anchor"><%=image_tag("gallery/pic8.jpg")%></a></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="footer-bottom">
      <div class="container">
         <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 text-center"> <a target="_blank" href="https://www.templateshub.net">Templates Hub</a></div>
         </div>
      </div>
   </div>
</footer>

app/views/layouts/_menu.html.erb
<div class="top-bar">
   <div class="container">
      <div class="row d-flex justify-content-between">
         <div class="topbar-left">
            <ul>
               <li><a href="javascript:;"><i class="fa fa-question-circle"></i>Ask a Question</a></li>
               <li><a href="javascript:;"><i class="fa fa-envelope-o"></i>twostep.dev@wgmail.com</a></li>
            </ul>
         </div>
         <div class="topbar-right">
            <ul>
               <li>
                  Wellcome: 
                  <%= link_to "#{ signed_in? ? current_user.fullname : "Guest"  }", current_user, class: "fullname" %>
               </li>
               <li>
                  <%= link_to_if(signed_in?, "Log out", logout_path, method: :delete) do %>
               <li><%= link_to "Login", login_path %></li>
               <li><%= link_to "Register", register_path %></li>
               <% end %>
               </li> 
            </ul>
         </div>
      </div>
   </div>
</div>
<div class="sticky-header navbar-expand-lg">
   <div class="menu-bar clearfix">
      <div class="container clearfix">
         <!-- Header Logo ==== -->
         <div class="menu-logo">
            <%=image_tag("logo.png")%> 
            </a>
         </div>
         <!-- Mobile Nav Button ==== -->
         <button class="navbar-toggler collapsed menuicon justify-content-end" type="button" data-toggle="collapse" data-target="#menuDropdown" aria-controls="menuDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span></span>
         <span></span>
         <span></span>
         </button>
         <!-- Author Nav ==== -->
         <div class="secondary-menu">
            <div class="secondary-inner">
               <ul>
                  <li><a href="javascript:;" class="btn-link"><i class="fab fa-facebook-f"></i></a></li>
                  <li><a href="javascript:;" class="btn-link"><i class="fab fa-google"></i></a></li>
                  <li><a href="javascript:;" class="btn-link"><i class="fab fa-linkedin"></i></a></li>
                  <!-- Search Button ==== -->
               </ul>
            </div>
         </div>
         <!-- Search Box ==== -->
         <div class="nav-search-bar">
            <form action="#">
               <input name="search" value="" type="text" class="form-control" placeholder="Type to search">
               <span><i class="ti-search"></i></span>
            </form>
            <span id="search-remove"><i class="ti-close"></i></span>
         </div>
         <!-- Navigation Menu ==== -->
         <div class="menu-links navbar-collapse collapse justify-content-start" id="menuDropdown">
            <div class="menu-logo">
               <a href="index.html">
               <%=image_tag("logo.png")%> 
               </a>
            </div>
            <ul class="nav navbar-nav">
               <li>
                  <%= link_to "Courses", root_path %>
               </li>
               <li>
                  <%= link_to_if(signed_in?, "Profile", current_user) do 
                     link_to "Profile", login_path 
                     end
                     %>
               </li>
               <% if signed_in? %>
               <% if current_user.role.eql?('admin') %>
               <li>
                  <a href="javascript:;">management<i class="fa fa-angle-right"></i></a>
                  <ul class="sub-menu">
                     <li><%= link_to 'New course', new_course_path  %></li>
                     <li class="divider"></li>
                     <li><%= link_to 'New subject', new_subject_path %></li>
                     <li><%= link_to 'Member List', users_path %></li>
                  </ul>
               </li>
               <% end %>
               <% end %>
            </ul>
            <div class="nav-social-link">
               <a href="javascript:;"><i class="fa fa-facebook"></i></a>
               <a href="javascript:;"><i class="fa fa-google-plus"></i></a>
               <a href="javascript:;"><i class="fa fa-linkedin"></i></a>
            </div>
         </div>
         <!-- Navigation Menu END ==== -->
      </div>
   </div>
</div>

app/views/layouts/_nav.html.erb
<div class="col-lg-3 col-md-4 col-sm-12 m-b30">
   <div class="widget courses-search-bx placeani">
      <div class="form-group">
         <div class="input-group">
            <form action="/courses">
               <input name="search" type="text" placeholder="Search Courses" required class="form-control">
            </form>
         </div>
      </div>
   </div>
   <div class="widget widget_archive">
      <h5 class="widget-title style-1">All Courses</h5>
      <ul>
         <li class="active"><a href="/">General</a></li>
         <li><a href="/courses?condition=IT - Software">IT - Software</a></li>
         <li><a href="/courses?condition=Photography">Photography</a></li>
         <li><a href="/courses?condition=Programming">Programming</a></li>
         <li><a href="/courses?condition=Technology">Technology</a></li>
      </ul>
   </div>
   <div class="widget recent-posts-entry widget-courses">
      <h5 class="widget-title style-1">NEW Courses</h5>
      <div class="widget-post-bx">
         <% @new_course.each do |course| %>
         <div class="widget-post clearfix">
            <div class="ttr-post-media"> 
               <%= image_tag course.thumb_url.url %>
            </div>
            <div class="ttr-post-info">
               <div class="ttr-post-header">
                  <h6><a class="course-title" href="/courses/<%= course.id %>"><%= course.title %></a></h6>
               </div>
               <div class="ttr-post-meta">
                  <ul>
                     <li class="price">
                        <h5>$<%= course.price %></h5>
                     </li>
                     <li class="review"><%= course.users_courses.count %> Joiner</li>
                  </ul>
               </div>
            </div>
         </div>
         <% end %>
      </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head class="header rs-nav">
      <title>ELearningV1</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
      <%= stylesheet_link_tag @locale_style unless @locale_style.nil? %>
      <%= csrf_meta_tags %>
      <% case request.env['REQUEST_PATH'] %>
      <% when "/register" %>
      <div></div>
      <% when "/login" %>
      <div></div>
      <% else %>
      <%= render 'layouts/menu'%>
      <% end %>
   </head>
   <body>
      <%= render 'messages/flash'%>
      <%= yield %>
      <% case request.env['REQUEST_PATH'] %>
      <% when "/register" %>
      <div></div>
      <% when "/login" %>
      <div></div>
      <% else %>
      <%= render 'layouts/footer'%>
      <% end %>
   </body>
</html>